sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/rdhyee/gitberg.git
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+git://github.com/rdhyee/pg-epubmaker.git
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kXdBVn6vXgHGc5CEIqJ8Q2WN0vBmq0go2yEZ2cdAz+MfQsYwNuCPsJmP+iHSmwWdTQy8d+go1jjTl3S7mozokxUPh938LVVp4D90poOiNSA/MHWvXLDCWSEQQQz/submcXG4PYdCOQdeUPkBYA3OyN6nHbGCqA4G19Xe5Dg9RNQfmzaeMQc49ItKTgc7ubleCwNtAsyXmN1CaKseIghgyXIlGXCIZ0qz3YlaLNyTgMOwfPS1VD6sUOCY8ZX9U++3suRR3ans6cU7FErXwh5rC10swFWRgMiKH2zFbfSO1Uq+XLC7/hLNGdXxW1VwbgmlE6hzDE4u1Btw4A26JgO+YUHx/RCiYulRXrN5jzuLEsp4YfxVlHoVbbYdZFd/zNxxs3r/jq75LYwqEjP0Xl59xK3MkyfrKdOMDjPfBIZSD0p9gYXy4npb/+jIFxOhZi0SppwES3jnDBfl/bnDSwuA6Hcy1y2epfOrvtAuP1gczyLAFua+W8n7RcKkXwkCykwNFk7rVg8a1phZHTDLmop8MRqrHwwVRtUgIpeEPDZ8b9VSteXOTSHbEIX9aAxr2og7/KgO6+WAcgVyUOtbfvrTfneg4wVmP9QU6FAHX2QkKZ2i31p+8gY8DoQsB9F6NiJhUa0FsTYSC1Ma6E+EaTlcyWjWNR+75ELa8JXZVnzaO3o=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: rdhyee/Frankenstein_84
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy